# Generated by Django 5.2.1 on 2025-05-27 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('meal', 'Meal'), ('office', 'Office Supplies'), ('other', 'Other')], max_length=20)),
                ('bill', models.FileField(upload_to='bills/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PM', 'Pending Manager'), ('PF', 'Pending Finance'), ('A', 'Approved'), ('R', 'Rejected')], default='PM', max_length=2)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('finance_comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
