# Generated by Django 5.2.1 on 2025-11-05 08:08

import apps.reimbursement.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_emails', models.TextField(blank=True, default='', help_text='Comma-separated admin email addresses for reimbursement summaries.')),
                ('finance_emails', models.TextField(blank=True, default='', help_text='Comma-separated default Finance recipients for reimbursement notifications.')),
                ('management_emails', models.TextField(blank=True, default='', help_text='Comma-separated default Management recipients for reimbursement notifications.')),
                ('require_management_approval', models.BooleanField(default=True, help_text='If enabled, requests must be approved by Management before Finance can pay.')),
                ('daily_digest_enabled', models.BooleanField(default=True, help_text='If enabled, send a daily reimbursement summary email to Admin.')),
                ('digest_hour_local', models.PositiveSmallIntegerField(default=9, help_text='Local hour (0–23, Asia/Kolkata) to send daily digest when enabled.')),
            ],
            options={
                'verbose_name': 'Reimbursement Settings',
                'verbose_name_plural': 'Reimbursement Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Legacy Reimbursement', 'verbose_name_plural': 'Legacy Reimbursements'},
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the expense was incurred.')),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('meal', 'Meal'), ('office', 'Office Supplies'), ('other', 'Other')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount must be greater than 0.', max_digits=10)),
                ('vendor', models.CharField(blank=True, default='', help_text='Merchant / vendor name (optional).', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Short description of the expense.')),
                ('receipt_file', models.FileField(help_text='Upload a jpg, png, or pdf (max size enforced by server).', upload_to=apps.reimbursement.models.receipt_upload_path, validators=[apps.reimbursement.models.validate_receipt_file])),
                ('status', models.CharField(choices=[('saved', 'Saved (Draft)'), ('attached', 'Attached to Request'), ('submitted', 'Submitted'), ('void', 'Voided')], db_index=True, default='saved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementApproverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(help_text='Employee who will submit reimbursement requests.', on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_approver_mapping', to=settings.AUTH_USER_MODEL)),
                ('finance', models.ForeignKey(blank=True, help_text="Finance contact responsible for processing this employee's reimbursements.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_finance_for', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsible for first-level reimbursement approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_manager_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reimbursement Approver Mapping',
                'verbose_name_plural': 'Reimbursement Approver Mappings',
            },
        ),
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was first submitted.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_manager', 'Pending Manager Approval'), ('pending_management', 'Pending Management Approval'), ('pending_finance', 'Pending Finance Review'), ('clarification_required', 'Clarification Required'), ('rejected', 'Rejected'), ('approved', 'Approved (Ready to Pay)'), ('paid', 'Paid')], db_index=True, default='pending_manager', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cached total of all included lines at submit time.', max_digits=12)),
                ('manager_decision', models.CharField(blank=True, default='', help_text='Manager decision: approved/rejected/clarification.', max_length=16)),
                ('manager_comment', models.TextField(blank=True, default='', help_text='Manager remarks visible to employee.')),
                ('manager_decided_at', models.DateTimeField(blank=True, null=True)),
                ('management_decision', models.CharField(blank=True, default='', help_text='Management decision: approved/rejected/clarification.', max_length=16)),
                ('management_comment', models.TextField(blank=True, default='', help_text='Management remarks visible to employee.')),
                ('management_decided_at', models.DateTimeField(blank=True, null=True)),
                ('finance_note', models.TextField(blank=True, default='', help_text='Internal finance notes.')),
                ('finance_payment_reference', models.CharField(blank=True, default='', help_text='External payment reference / transaction ID.', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When Finance marked this request as Paid.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_notified_admin_at', models.DateTimeField(blank=True, help_text='Last time an admin summary was sent for this request.', null=True)),
                ('created_by', models.ForeignKey(help_text='Employee who submitted the reimbursement.', on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_requests', to=settings.AUTH_USER_MODEL)),
                ('management', models.ForeignKey(blank=True, help_text='Higher-level management approver (second-level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_as_management', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Line manager / reporting person for first-level approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_as_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('status_changed', 'Status Changed'), ('commented', 'Comment Added'), ('clarification_requested', 'Clarification Requested'), ('paid', 'Marked Paid'), ('email_sent', 'Email Sent')], db_index=True, max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_logs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reimbursement.reimbursementrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Captured at time of submission (copied from ExpenseItem).', max_digits=10)),
                ('description', models.TextField(blank=True, default='', help_text='Captured at time of submission (copied from ExpenseItem).')),
                ('receipt_file', models.FileField(blank=True, help_text='Snapshot of the receipt file when submitted (optional).', null=True, upload_to=apps.reimbursement.models.receipt_upload_path, validators=[apps.reimbursement.models.validate_receipt_file])),
                ('status', models.CharField(choices=[('included', 'Included'), ('removed', 'Removed')], db_index=True, default='included', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_item', models.ForeignKey(help_text='Source ExpenseItem used for this line.', on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='reimbursement.expenseitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reimbursement.reimbursementrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['created_by', 'status'], name='reimburseme_created_befd64_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['date'], name='reimburseme_date_aa226a_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementrequest',
            index=models.Index(fields=['status'], name='reimburseme_status_8bb720_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementrequest',
            index=models.Index(fields=['created_by', 'status'], name='reimburseme_created_0fc9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementlog',
            index=models.Index(fields=['request', 'action'], name='reimburseme_request_f97aea_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementline',
            index=models.Index(fields=['request', 'status'], name='reimburseme_request_312cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementline',
            index=models.Index(fields=['expense_item'], name='reimburseme_expense_32e8bd_idx'),
        ),
    ]
