# Generated by Django 5.2.1 on 2025-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_reimbursementsettings_alter_reimbursement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementsettings',
            name='approver_bcc_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated BCC emails for second-level approval notification (e.g. vilas@blueoceansteels.com).'),
        ),
        migrations.AddField(
            model_name='reimbursementsettings',
            name='approver_cc_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CC emails for second-level approval notification (e.g. amreen@blueoceansteels.com).'),
        ),
        migrations.AddField(
            model_name='reimbursementsettings',
            name='approver_level1_email',
            field=models.EmailField(blank=True, default='', help_text='Global first approver email for new reimbursement requests (e.g. vilas@blueoceansteels.com). If blank, system falls back to per-employee Manager mapping.', max_length=254),
        ),
        migrations.AddField(
            model_name='reimbursementsettings',
            name='approver_level2_email',
            field=models.EmailField(blank=True, default='', help_text='Global second approver email to notify after Level-1 approval (e.g. akshay@blueoceansteels.com).', max_length=254),
        ),
    ]
