# Generated by Django 5.2.1 on 2025-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_reimbursementsettings_approver_bcc_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_bcc_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated BCC emails for the Level-2 notification (e.g. vilas@blueoceansteels.com).'),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_cc_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated CC emails for the Level-2 notification (e.g. amreen@blueoceansteels.com, akshay@blueoceansteels.com).'),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_level1_email',
            field=models.EmailField(blank=True, default='', help_text='Global first approver email for new reimbursement requests (e.g. vilas@blueoceansteels.com). If blank, the system falls back to per-employee Manager mapping.', max_length=254),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_level2_email',
            field=models.EmailField(blank=True, default='', help_text='Primary Level-2 approver email after Level-1 approval (e.g. main Mumbai accounts email).', max_length=254),
        ),
    ]
