# Generated by Django 5.2.1 on 2025-11-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_expenseitem_gst_type_alter_expenseitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel Expenses'), ('meal', 'Food Expenses'), ('yard', 'Yard Expenses'), ('office', 'Office Supplies'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='gst_type',
            field=models.CharField(choices=[('gst', 'GST Bill'), ('non_gst', 'Non GST Bill')], default='non_gst', help_text='Whether this bill is under GST or not (GST Bill / Non GST Bill).', max_length=10),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel Expenses'), ('meal', 'Food Expenses'), ('yard', 'Yard Expenses'), ('office', 'Office Supplies'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_manager', 'Pending Manager Approval'), ('pending_management', 'Pending Management Approval'), ('pending_finance', 'Pending Finance Review'), ('clarification_required', 'Clarification Required'), ('rejected', 'Rejected'), ('approved', 'Approved (Ready to Pay)'), ('paid', 'Paid')], db_index=True, default='pending_manager', max_length=32),
        ),
    ]
