# Generated by Django 5.2.1 on 2025-11-14 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_alter_expenseitem_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When Finance marked this request as Verified.', null=True),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Finance user who verified the reimbursement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('verified', 'Verified by Finance'), ('manager_approved', 'Approved by Manager'), ('status_changed', 'Status Changed'), ('commented', 'Comment Added'), ('clarification_requested', 'Clarification Requested'), ('paid', 'Marked Paid'), ('email_sent', 'Email Sent')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_finance_verify', 'Pending Finance Verification'), ('pending_manager', 'Pending Manager Approval'), ('pending_management', 'Pending Management Approval'), ('pending_finance', 'Pending Finance Review'), ('clarification_required', 'Clarification Required'), ('rejected', 'Rejected'), ('approved', 'Approved (Ready to Pay)'), ('paid', 'Paid')], db_index=True, default='pending_finance_verify', max_length=32),
        ),
    ]
