# Generated by Django 5.2.1 on 2025-12-25 04:38

import apps.reimbursement.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0007_reimbursementrequest_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='gst_type',
            field=models.CharField(choices=[('gst', 'GST Bill'), ('non_gst', 'Non GST Bill')], default='non_gst', max_length=10),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='receipt_file',
            field=models.FileField(upload_to=apps.reimbursement.models.receipt_upload_path, validators=[apps.reimbursement.models.validate_receipt_file]),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reimbursementapprovermapping',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_approver_mapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementapprovermapping',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_finance_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementapprovermapping',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_manager_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reimbursementline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementline',
            name='expense_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='reimbursement.expenseitem'),
        ),
        migrations.AlterField(
            model_name='reimbursementline',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.reimbursement.models.receipt_upload_path, validators=[apps.reimbursement.models.validate_receipt_file]),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='finance_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='finance_payment_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='last_notified_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_as_management', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='management_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='management_decision',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_as_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='manager_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='manager_decision',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='admin_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_bcc_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_cc_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_level1_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='approver_level2_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='daily_digest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='digest_hour_local',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='finance_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='management_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='require_management_approval',
            field=models.BooleanField(default=True),
        ),
    ]
