# Generated by Django 5.2.1 on 2025-12-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0008_alter_expenseitem_amount_alter_expenseitem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('verified', 'Verified by Finance'), ('manager_approved', 'Approved by Manager'), ('status_changed', 'Status Changed'), ('commented', 'Comment Added'), ('clarification_requested', 'Clarification Requested'), ('paid', 'Marked Paid'), ('email_sent', 'Email Sent'), ('reversed', 'Reversed to Finance Verification')], db_index=True, max_length=32),
        ),
    ]
