# Generated by Django 5.2.1 on 2026-01-02 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0009_alter_reimbursementlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementline',
            name='bill_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('employee_resubmitted', 'Employee Resubmitted'), ('manager_approved', 'Manager Approved'), ('paid', 'Paid')], db_index=True, default='submitted', max_length=32),
        ),
        migrations.AddField(
            model_name='reimbursementline',
            name='finance_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reimbursementline',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_reimbursement_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursementline',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursementline',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_rejected_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_finance_verify', 'Pending Finance Verification'), ('pending_manager', 'Pending Manager Approval'), ('pending_management', 'Pending Management Approval'), ('pending_finance', 'Pending Finance Review'), ('partial_hold', 'Partial Hold (Finance)'), ('partially_rejected', 'Partially Rejected (Back to Employee)'), ('clarification_required', 'Clarification Required'), ('rejected', 'Rejected'), ('approved', 'Approved (Ready to Pay)'), ('paid', 'Paid')], db_index=True, default='pending_finance_verify', max_length=32),
        ),
        migrations.AddIndex(
            model_name='reimbursementline',
            index=models.Index(fields=['request', 'bill_status'], name='reimburseme_request_26f400_idx'),
        ),
    ]
