# Generated by Django 5.2.1 on 2026-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0010_reimbursementline_bill_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
