# Generated by Django 5.2.1 on 2026-01-09 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0011_reimbursementline_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementline',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursementline',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reimbursementline',
            name='bill_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Finance Rejected'), ('employee_resubmitted', 'Employee Resubmitted'), ('manager_pending', 'Pending Manager Approval'), ('manager_rejected', 'Manager Rejected'), ('manager_approved', 'Manager Approved'), ('paid', 'Paid')], db_index=True, default='submitted', max_length=32),
        ),
        migrations.AddIndex(
            model_name='reimbursementline',
            index=models.Index(fields=['bill_status', 'updated_at'], name='reimburseme_bill_st_c2bd3b_idx'),
        ),
    ]
