# Generated by Django 5.2.1 on 2026-01-16 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0012_reimbursementline_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reimbursementrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), models.Q(('paid_at__isnull', False), models.Q(('finance_payment_reference', ''), _negated=True)), _connector='OR'), name='rr_paid_requires_reference_and_timestamp'),
        ),
    ]
