# Generated by Django 5.2.1 on 2026-02-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0013_reimbursementrequest_rr_paid_requires_reference_and_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Legacy Reimbursement', 'verbose_name_plural': 'Legacy Legacy Reimbursements'},
        ),
    ]
