# Generated by Django 5.2.1 on 2026-03-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0014_alter_reimbursement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Legacy Reimbursement', 'verbose_name_plural': 'Legacy Reimbursements'},
        ),
    ]
