# Generated by Django 5.2.1 on 2026-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0015_alter_reimbursement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementsettings',
            name='submitted_notify_cc_emails',
            field=models.TextField(blank=True, default='amreen@blueoceansteels.com,akshay@blueoceansteels.com,sharyu@blueoceansteels.com', help_text='CC recipients for the submission notification email. Comma-separated. E.g. amreen@blueoceansteels.com, akshay@blueoceansteels.com'),
        ),
        migrations.AddField(
            model_name='reimbursementsettings',
            name='submitted_notify_to_emails',
            field=models.TextField(blank=True, default='vilas@blueoceansteels.com', help_text='TO recipients for the submission notification email. Comma-separated. E.g. vilas@blueoceansteels.com'),
        ),
    ]
