# Generated by Django 5.2.1 on 2026-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0017_approver_mapping_fk_to_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementsettings',
            name='submitted_notify_cc_emails',
            field=models.TextField(blank=True, default='amreen@blueoceansteels.com,akshay@blueoceansteels.com,sharyu@blueoceansteels.com', help_text='CC recipients for the submission notification email. Comma-separated.'),
        ),
    ]
