# Generated by Django 5.2.1 on 2026-06-14 12:13

import apps.reimbursement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0018_alter_reimbursementsettings_submitted_notify_cc_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='bank_attachment',
            field=models.FileField(blank=True, help_text='Optional bank details attachment uploaded by employee.', null=True, upload_to=apps.reimbursement.models.bank_attachment_upload_path, validators=[apps.reimbursement.models.validate_bank_attachment_file]),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='bank_details',
            field=models.TextField(blank=True, default='', help_text='Bank details entered by employee for reimbursement payment.'),
        ),
        migrations.AddField(
            model_name='reimbursementline',
            name='bank_attachment',
            field=models.FileField(blank=True, help_text='Bank details attachment copied from the uploaded expense.', null=True, upload_to=apps.reimbursement.models.bank_attachment_upload_path, validators=[apps.reimbursement.models.validate_bank_attachment_file]),
        ),
        migrations.AddField(
            model_name='reimbursementline',
            name='bank_details',
            field=models.TextField(blank=True, default='', help_text='Bank details copied from the uploaded expense.'),
        ),
    ]
