# Generated by Django 5.2.1 on 2025-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleskpi_metric_customer_saleskpi_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleskpi',
            name='kam',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saleskpi',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saleskpi',
            name='month',
            field=models.CharField(blank=True, choices=[('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('January', 'January'), ('February', 'February'), ('March', 'March')], max_length=16),
        ),
        migrations.AddField(
            model_name='saleskpi',
            name='round_bar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleskpi',
            name='total_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleskpi',
            name='week',
            field=models.CharField(blank=True, choices=[('Week-1', 'Week-1'), ('Week-2', 'Week-2'), ('Week-3', 'Week-3'), ('Week-4', 'Week-4'), ('Week-5', 'Week-5')], max_length=16),
        ),
        migrations.AddField(
            model_name='saleskpi',
            name='wire_rod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleskpi',
            name='wr_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='WR Actual'),
        ),
    ]
