# Generated by Django 5.2.1 on 2025-08-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleskpi_kam_saleskpi_location_saleskpi_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleskpi',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=16),
        ),
    ]
