# Generated by Django 5.2.1 on 2025-05-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('checklist', 'Checklist'), ('delegation', 'Delegation')], max_length=20)),
                ('csv_file', models.FileField(upload_to='bulk_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('planned_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('attachment_mandatory', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('remind_before_days', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('media_upload', models.FileField(blank=True, null=True, upload_to='checklist_media/')),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('set_reminder', models.BooleanField(default=False)),
                ('reminder_mode', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10)),
                ('reminder_frequency', models.PositiveIntegerField(blank=True, default=1)),
                ('reminder_before_days', models.PositiveIntegerField(blank=True, default=0)),
                ('reminder_starting_time', models.TimeField(blank=True, null=True)),
                ('checklist_auto_close', models.BooleanField(default=False)),
                ('checklist_auto_close_days', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_assigned', to=settings.AUTH_USER_MODEL)),
                ('assign_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_checklists', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_checklists', to=settings.AUTH_USER_MODEL)),
                ('notify_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_checklists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('planned_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('attachment_mandatory', models.BooleanField(default=False)),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='delegation_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assign_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_assigned', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
