# Generated by Django 4.2 on 2025-01-XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]