# Generated by Django 5.2.1 on 2025-06-25 09:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
