# Generated by Django 5.2.1 on 2025-06-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
