# Generated by Django 5.2.1 on 2025-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_helpticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delegation',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fms',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
