# Generated by Django 5.2.1 on 2025-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_weeklycommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='actual_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
