# Generated by Django 5.2.1 on 2025-06-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_checklist_actual_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='actual_minutes',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='assign_pc',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='attachment_mandatory',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_auto_close',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_auto_close_days',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='estimated_minutes',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='media_upload',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='message',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='notify_to',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='remind_before_days',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='reminder_before_days',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='reminder_frequency',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='reminder_mode',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='reminder_starting_time',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='set_reminder',
        ),
        migrations.AddField(
            model_name='checklist',
            name='time_per_task_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes per occurrence'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='Repetition interval (e.g. every N days/weeks)'),
        ),
    ]
