# Generated by Django 5.2.1 on 2025-06-24 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_checklist_actual_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='assign_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='attachment_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_auto_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_auto_close_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='checklist',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checklist',
            name='media_upload',
            field=models.FileField(blank=True, null=True, upload_to='checklist_media/'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='notify_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='remind_before_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reminder_before_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reminder_frequency',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reminder_mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reminder_starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='set_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='time_per_task_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Enter how many minutes this task takes each time it runs'),
        ),
    ]
