# Generated by Django 5.2.1 on 2025-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_add_time_per_task_to_delegation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='estimated_minutes',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='time_per_task_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes required each time this checklist runs'),
        ),
        migrations.DeleteModel(
            name='WeeklyCommitment',
        ),
    ]
