# Generated by Django 5.2.1 on 2025-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_completed_fields'),
        ('tasks', '0012_remove_delegation_estimated_minutes_and_more'),
    ]

    operations = [
    ]
