# Generated by Django 5.2.1 on 2025-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_merge_20250625_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='media_upload',
            field=models.FileField(blank=True, null=True, upload_to='help_ticket_media/'),
        ),
    ]
