# Generated by Django 5.2.1 on 2025-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_helpticket_priority_helpticket_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='doer_file',
            field=models.FileField(blank=True, null=True, upload_to='checklist_uploads/'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='doer_notes',
            field=models.TextField(blank=True),
        ),
    ]
