# Generated by Django 5.2.1 on 2025-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_checklist_doer_file_checklist_doer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='doer_file',
            field=models.FileField(blank=True, null=True, upload_to='delegation_doer_files/'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='doer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='doer_file',
            field=models.FileField(blank=True, null=True, upload_to='checklist_doer_files/'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='doer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='time_per_task_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='time_per_task_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
