# Generated by Django 5.2.1 on 2025-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_delegation_completed_at_delegation_doer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fms',
            name='doer_file',
            field=models.FileField(blank=True, null=True, upload_to='fms_doer/'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='doer_file',
            field=models.FileField(blank=True, null=True, upload_to='checklist_doer/'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='doer_file',
            field=models.FileField(blank=True, null=True, upload_to='delegation_doer/'),
        ),
    ]
