# Generated by Django 5.2.1 on 2025-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_fms_doer_file_alter_checklist_doer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='delegation',
            name='mode',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=10),
        ),
    ]
