# Generated by Django 5.2.1 on 2025-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_delegation_frequency_delegation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
