# Generated by Django 5.2.1 on 2025-08-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_delegation_actual_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_auto_close_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='remind_before_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='reminder_before_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='reminder_frequency',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='reminder_mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='time_per_task_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='time_per_task_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
