# Generated by Django 5.2.1 on 2025-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_checklist_checklist_auto_close_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='planned_date',
            field=models.DateTimeField(),
        ),
    ]
