# Generated by Django 5.2.1 on 2025-08-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_merge_0002_0023'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checklist',
            name='chk_status_planned_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='chk_assignto_planned_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='chk_assignto_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='chk_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='delegation',
            name='dlg_status_planned_idx',
        ),
        migrations.RemoveIndex(
            model_name='delegation',
            name='dlg_assignto_planned_idx',
        ),
        migrations.RemoveIndex(
            model_name='delegation',
            name='dlg_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='helpticket',
            name='ht_status_planned_idx',
        ),
        migrations.RemoveIndex(
            model_name='helpticket',
            name='ht_assignto_planned_idx',
        ),
    ]
