# Generated by Django 5.2.1 on 2025-08-19 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_checklist_chk_status_planned_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='group_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], db_index=True, default='Daily', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fms',
            name='planned_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fms',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['assign_to', 'status', 'planned_date'], name='tasks_check_assign__fea7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['mode', 'frequency'], name='tasks_check_mode_b1bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['group_name'], name='tasks_check_group_n_18a943_idx'),
        ),
        migrations.AddIndex(
            model_name='delegation',
            index=models.Index(fields=['assign_to', 'status', 'planned_date'], name='tasks_deleg_assign__1d16d5_idx'),
        ),
        migrations.AddIndex(
            model_name='delegation',
            index=models.Index(fields=['mode', 'frequency'], name='tasks_deleg_mode_884fd3_idx'),
        ),
    ]
