# Generated by Django 5.2.1 on 2025-08-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_delegation_updated_at_alter_checklist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checklist',
            name='tasks_check_assign__fea7ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='tasks_check_mode_b1bbe9_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='tasks_check_group_n_18a943_idx',
        ),
        migrations.RemoveIndex(
            model_name='delegation',
            name='tasks_deleg_assign__1d16d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='delegation',
            name='tasks_deleg_mode_884fd3_idx',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='planned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='planned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fms',
            name='planned_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fms',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='planned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
