# Generated by Django 5.2.1 on 2025-08-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_remove_checklist_tasks_check_assign__fea7ec_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='reminder_before_days',
        ),
        migrations.AlterField(
            model_name='delegation',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='mode',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default=None, max_length=10, null=True),
        ),
    ]
