# Generated by Django 5.2.1 on 2025-08-27 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_remove_checklist_reminder_before_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Stop creating new occurrences after this date.', null=True),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['assign_to', 'task_name', 'mode', 'frequency', 'group_name'], name='tasks_check_assign__d3f05c_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['assign_to', 'status', 'planned_date'], name='tasks_check_assign__fea7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['status', 'planned_date'], name='tasks_check_status_fac3be_idx'),
        ),
        migrations.AddIndex(
            model_name='delegation',
            index=models.Index(fields=['assign_to', 'status', 'planned_date'], name='tasks_deleg_assign__1d16d5_idx'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['assign_to', 'status', 'planned_date'], name='tasks_helpt_assign__a64c6b_idx'),
        ),
    ]
