# Generated by Django 5.2.1 on 2025-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_checklist_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-planned_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='delegation',
            options={'ordering': ['-planned_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='fms',
            options={'ordering': ['-planned_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='helpticket',
            options={'ordering': ['-planned_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fms',
            name='planned_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fms',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=20),
        ),
    ]
