# Generated by Django 5.2.1 on 2025-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_bulkupload_options_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
