# Generated by Django 5.2.1 on 2025-09-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_delegation_message'),
        ('tasks', '0031_delegation_description'),
    ]

    operations = [
    ]
