# Generated by Django 5.2.1 on 2025-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_merge_20250922_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkupload',
            options={},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='delegation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='helpticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='description',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='planned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='planned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fms',
            name='planned_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fms',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fms',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='planned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
