# Generated by Django 5.2.1 on 2025-10-10 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_delegation_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_skipped_due_to_leave',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='delegation',
            name='is_skipped_due_to_leave',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='fms',
            name='is_skipped_due_to_leave',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='is_skipped_due_to_leave',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['is_skipped_due_to_leave', 'planned_date'], name='tasks_check_is_skip_422214_idx'),
        ),
        migrations.AddIndex(
            model_name='delegation',
            index=models.Index(fields=['is_skipped_due_to_leave', 'planned_date'], name='tasks_deleg_is_skip_fde1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='fms',
            index=models.Index(fields=['assign_to', 'status', 'planned_date'], name='tasks_fms_assign__bcad1f_idx'),
        ),
        migrations.AddIndex(
            model_name='fms',
            index=models.Index(fields=['is_skipped_due_to_leave', 'planned_date'], name='tasks_fms_is_skip_3fbf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['is_skipped_due_to_leave', 'planned_date'], name='tasks_helpt_is_skip_57ed82_idx'),
        ),
    ]
