# Generated by Django 5.2.1 on 2025-11-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_checklist_is_skipped_due_to_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='delegation_auto_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delegation',
            name='delegation_auto_close_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='reminder_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='reminder_mode',
            field=models.CharField(blank=True, choices=[('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Days', 'Days')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='reminder_starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='set_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
