# Generated by Django 5.2.1 on 2025-11-04 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_delegation_delegation_auto_close_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='delegation_auto_close',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='delegation_auto_close_days',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='reminder_frequency',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='reminder_mode',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='reminder_starting_time',
        ),
        migrations.AddField(
            model_name='delegation',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='delegation',
            index=models.Index(fields=['status', 'set_reminder', 'reminder_time'], name='tasks_deleg_status_fd17fb_idx'),
        ),
    ]
