# Generated by Django 5.2.1 on 2025-11-10 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_remove_delegation_delegation_auto_close_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text='Optional users to keep in CC for this delegation.', related_name='delegations_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
