# Generated by Django 5.2.1 on 2026-05-08 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_delegation_cc_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='checklist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_checklist_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['is_deleted', 'is_active', 'planned_date'], name='tasks_check_is_dele_42750a_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['assign_to', 'is_deleted', 'is_active'], name='tasks_check_assign__67fa7a_idx'),
        ),
    ]
