# Generated by Django 5.2.1 on 2026-08-01 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_checklist_delete_reason_checklist_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistRecurringSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('first_planned_date', models.DateTimeField()),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('attachment_mandatory', models.BooleanField(default=False)),
                ('time_per_task_minutes', models.PositiveIntegerField(default=0)),
                ('remind_before_days', models.PositiveIntegerField(default=0)),
                ('set_reminder', models.BooleanField(default=False)),
                ('reminder_mode', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True)),
                ('reminder_frequency', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('reminder_starting_time', models.TimeField(blank=True, null=True)),
                ('checklist_auto_close', models.BooleanField(default=False)),
                ('checklist_auto_close_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_series_created', to=settings.AUTH_USER_MODEL)),
                ('assign_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_checklist_series', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_recurring_series', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_checklist_series', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_checklist_series', to=settings.AUTH_USER_MODEL)),
                ('notify_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_checklist_series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='recurring_series',
            field=models.ForeignKey(blank=True, help_text='Recurring master that generated this occurrence.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tasks.checklistrecurringseries'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['recurring_series', 'status', 'planned_date'], name='tasks_check_recurri_cda76f_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrecurringseries',
            index=models.Index(fields=['is_active', 'is_deleted', 'next_run_at'], name='cl_series_due_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistrecurringseries',
            index=models.Index(fields=['assign_to', 'task_name'], name='cl_series_owner_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistrecurringseries',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assign_to', 'task_name', 'mode', 'frequency', 'group_name'), name='uniq_live_checklist_series'),
        ),
        migrations.AddConstraint(
            model_name='checklistrecurringseries',
            constraint=models.CheckConstraint(condition=models.Q(('frequency__gte', 1)), name='checklist_series_frequency_gte_1'),
        ),
    ]
