# Generated by Django 5.2.1 on 2026-08-01 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_checklistrecurringseries_checklist_recurring_series_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='delegation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='fms',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fms',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fms',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fms',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='fms',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='delegation',
            index=models.Index(fields=['is_deleted', 'is_active', 'planned_date'], name='tasks_deleg_is_dele_7d595f_idx'),
        ),
        migrations.AddIndex(
            model_name='delegation',
            index=models.Index(fields=['assign_to', 'is_deleted', 'is_active'], name='tasks_deleg_assign__351835_idx'),
        ),
        migrations.AddIndex(
            model_name='fms',
            index=models.Index(fields=['is_deleted', 'is_active', 'planned_date'], name='tasks_fms_is_dele_f4264c_idx'),
        ),
        migrations.AddIndex(
            model_name='fms',
            index=models.Index(fields=['assign_to', 'is_deleted', 'is_active'], name='tasks_fms_assign__09ebc9_idx'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['is_deleted', 'is_active', 'planned_date'], name='tasks_helpt_is_dele_28f23e_idx'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['assign_to', 'is_deleted', 'is_active'], name='tasks_helpt_assign__92a06e_idx'),
        ),
    ]
