# Generated by Django 5.2.1 on 2026-07-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_link_employee_to_user_add_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_officer',
            field=models.ForeignKey(blank=True, help_text='Reporting manager. Admin-managed single source of truth for leave routing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_master_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['reporting_officer'], name='recruitment_reporti_7a9d9f_idx'),
        ),
    ]
