# Generated by Django 5.2.1 on 2025-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Manager Approved', 'Manager Approved'), ('Manager Rejected', 'Manager Rejected'), ('Finance Approved', 'Finance Approved'), ('Finance Rejected', 'Finance Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pettycashrequest',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
