# Generated by Django 5.2.1 on 2026-01-29 08:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('pincode', models.CharField(blank=True, max_length=12, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('agreed_credit_period_days', models.IntegerField(default=0)),
                ('primary_kam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode', models.CharField(blank=True, max_length=32, null=True)),
                ('reference', models.CharField(blank=True, max_length=64, null=True)),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=64, null=True)),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('invoice_date', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('qty_mt', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue_gst', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('doe', models.DateField()),
                ('qty_mt', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=32)),
                ('grade', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month')], max_length=8)),
                ('period_id', models.CharField(max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_headers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_target_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('visits_target', models.IntegerField(default=6)),
                ('calls_target', models.IntegerField(default=24)),
                ('leads_target_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('nbd_target_monthly', models.IntegerField(default=0)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kam.targetheader')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kam_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('PLANNED', 'Planned'), ('UNPLANNED', 'Unplanned')], max_length=12)),
                ('purpose', models.CharField(blank=True, max_length=128, null=True)),
                ('expected_sales_mt', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('expected_collection', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('not_success_reason', models.CharField(blank=True, choices=[('PRICE', 'Price'), ('MILL_NOT_APPROVED', 'Mill not approved'), ('QUALITY', 'Quality'), ('CREDIT_TERMS', 'Credit / payment terms'), ('OTHER', 'Other')], max_length=32, null=True)),
                ('actual_sales_mt', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actual_collection', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('reminder_cc_manager', models.BooleanField(default=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='kam.visitplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KAMAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kam.customer')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'kam', 'active_from'], name='kam_kamassi_custome_045606_idx')],
            },
        ),
        migrations.CreateModel(
            name='KpiSnapshotDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('sales_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('collection_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('visits_planned', models.IntegerField(default=0)),
                ('visits_actual', models.IntegerField(default=0)),
                ('calls', models.IntegerField(default=0)),
                ('leads_total_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('leads_won_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('nbd_won_count', models.IntegerField(default=0)),
                ('overdue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exposure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('snapshot_date', 'kam')},
            },
        ),
        migrations.CreateModel(
            name='OverdueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('exposure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overdue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ageing_0_30', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ageing_31_60', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ageing_61_90', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ageing_90_plus', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
            ],
            options={
                'unique_together': {('snapshot_date', 'customer')},
            },
        ),
    ]
