# Generated by Django 5.2.1 on 2026-01-31 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scope', models.CharField(choices=[('SELF', 'Self'), ('TEAM', 'Team')], default='SELF', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('last_customer_cursor', models.CharField(blank=True, max_length=128, null=True)),
                ('last_invoice_cursor', models.CharField(blank=True, max_length=128, null=True)),
                ('last_lead_cursor', models.CharField(blank=True, max_length=128, null=True)),
                ('last_overdue_cursor', models.CharField(blank=True, max_length=128, null=True)),
                ('step_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitApprovalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='targetline',
            name='collections_plan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterUniqueTogether(
            name='targetheader',
            unique_together={('period_type', 'period_id')},
        ),
        migrations.AlterUniqueTogether(
            name='targetline',
            unique_together={('header', 'kam')},
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['kam', 'call_datetime'], name='kam_calllog_kam_id_ff19f3_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiontxn',
            index=models.Index(fields=['kam', 'txn_datetime'], name='kam_collect_kam_id_036233_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['kam', 'visit_date'], name='kam_visitpl_kam_id_ca0ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['approval_status'], name='kam_visitpl_approva_b9fb48_idx'),
        ),
        migrations.AddField(
            model_name='syncintent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kam_sync_intents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitapprovalaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitapprovalaudit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_audits', to='kam.visitplan'),
        ),
        migrations.AddIndex(
            model_name='syncintent',
            index=models.Index(fields=['status', 'created_at'], name='kam_syncint_status_d4441d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitapprovalaudit',
            index=models.Index(fields=['plan', 'created_at'], name='kam_visitap_plan_id_5c0e67_idx'),
        ),
    ]
