# Generated by Django 5.2.1 on 2026-02-01 07:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0002_syncintent_visitapprovalaudit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncintent',
            name='last_collection_cursor',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='syncintent',
            name='last_nbd_cursor',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='targetline',
            name='leads_target_mt',
            field=models.DecimalField(decimal_places=3, default=250, max_digits=12),
        ),
        migrations.AlterField(
            model_name='targetline',
            name='nbd_target_monthly',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='CollectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month')], max_length=8)),
                ('period_id', models.CharField(max_length=10)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kam', 'period_type', 'period_id'], name='kam_collect_kam_id_38afd3_idx')],
                'unique_together': {('period_type', 'period_id', 'customer', 'kam')},
            },
        ),
        migrations.CreateModel(
            name='NbdFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kam.customer')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kam', 'date'], name='kam_nbdfact_kam_id_cf28d1_idx')],
            },
        ),
    ]
