# Generated by Django 5.2.1 on 2026-02-01 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0003_syncintent_last_collection_cursor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbdfact',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='nbdfact',
            name='kam',
        ),
        migrations.RemoveIndex(
            model_name='collectionplan',
            name='kam_collect_kam_id_38afd3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='collectionplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='syncintent',
            name='last_collection_cursor',
        ),
        migrations.RemoveField(
            model_name='syncintent',
            name='last_nbd_cursor',
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='period_type',
            field=models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month'), ('QUARTER', 'Quarter'), ('YEAR', 'Year')], max_length=8),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='targetheader',
            name='period_type',
            field=models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month'), ('QUARTER', 'Quarter'), ('YEAR', 'Year')], max_length=8),
        ),
        migrations.AlterField(
            model_name='targetline',
            name='leads_target_mt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='collectionplan',
            unique_together={('period_type', 'period_id', 'customer')},
        ),
        migrations.DeleteModel(
            name='NbdFact',
        ),
    ]
