# Generated by Django 5.2.1 on 2026-02-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0004_remove_nbdfact_customer_remove_nbdfact_kam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_nbd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='visit_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetline',
            name='nbd_target_monthly',
            field=models.IntegerField(default=0),
        ),
    ]
