# Generated by Django 5.2.1 on 2026-02-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0005_customer_contact_person_customer_is_nbd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('access_kam_module', 'Can access KAM module')]},
        ),
    ]
