# Generated by Django 5.2.1 on 2026-02-03 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0006_alter_customer_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('visit_category', models.CharField(choices=[('CUSTOMER', 'Customer Visit'), ('SUPPLIER', 'Supplier Visit'), ('WAREHOUSE', 'Warehouse Visit')], max_length=16)),
                ('purpose', models.CharField(blank=True, max_length=128, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='visitapprovalaudit',
            name='kam_visitap_plan_id_5c0e67_idx',
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitactual',
            name='confirmed_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='counterparty_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='visit_category',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Visit'), ('SUPPLIER', 'Supplier Visit'), ('WAREHOUSE', 'Warehouse Visit')], default='CUSTOMER', max_length=16),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='period_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='period_type',
            field=models.CharField(blank=True, choices=[('WEEK', 'Week'), ('MONTH', 'Month'), ('QUARTER', 'Quarter'), ('YEAR', 'Year')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='visitapprovalaudit',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_audits', to='kam.visitplan'),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kam.customer'),
        ),
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['from_date', 'to_date', 'customer'], name='kam_collect_from_da_65c6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['kam'], name='kam_collect_kam_id_3161c2_idx'),
        ),
        migrations.AddField(
            model_name='visitbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitbatch',
            name='kam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitapprovalaudit',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_audits', to='kam.visitbatch'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kam.visitbatch'),
        ),
        migrations.AddIndex(
            model_name='visitapprovalaudit',
            index=models.Index(fields=['created_at'], name='kam_visitap_created_b088c3_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['batch'], name='kam_visitpl_batch_i_0c3254_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['visit_category'], name='kam_visitpl_visit_c_31ac7a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitbatch',
            index=models.Index(fields=['kam', 'from_date', 'to_date'], name='kam_visitba_kam_id_a38b24_idx'),
        ),
        migrations.AddIndex(
            model_name='visitbatch',
            index=models.Index(fields=['approval_status'], name='kam_visitba_approva_c736f8_idx'),
        ),
    ]
