# Generated by Django 5.2.1 on 2026-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0007_visitbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='visitbatch',
            name='visit_category',
            field=models.CharField(choices=[('VENDOR', 'Vendor Visit'), ('CUSTOMER', 'Customer Visit'), ('SUPPLIER', 'Supplier Visit'), ('WAREHOUSE', 'Warehouse Visit')], max_length=16),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='visit_category',
            field=models.CharField(choices=[('VENDOR', 'Vendor Visit'), ('CUSTOMER', 'Customer Visit'), ('SUPPLIER', 'Supplier Visit'), ('WAREHOUSE', 'Warehouse Visit')], default='CUSTOMER', max_length=16),
        ),
    ]
