# Generated by Django 5.2.1 on 2026-02-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0002_target_setting'),
        ('kam', '0008_customer_code_alter_visitbatch_visit_category_and_more'),
    ]

    operations = [
    ]
