# Generated by Django 5.2.1 on 2026-02-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0009_merge_0002_target_setting_0008_customer_code_alter_visitbatch_visit_category_and_more'),
        ('kam', '0009_merge_20260218_1320'),
    ]

    operations = [
    ]
