# Generated by Django 5.2.1 on 2026-02-18 12:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0010_merge_20260218_1337'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTargetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField(db_index=True)),
                ('to_date', models.DateField(db_index=True)),
                ('sales_target', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('collection_target', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('collection_mode', models.CharField(choices=[('VALUE', 'Manual Value'), ('PERCENT', '% of Overdue')], default='VALUE', max_length=10)),
                ('collection_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('calls_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('visit_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('leads_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nbd_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_fixed', models.BooleanField(default=False)),
                ('fixed_expiry_date', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameIndex(
            model_name='targetsetting',
            new_name='kam_targets_kam_id_dea8ff_idx',
            old_name='kam_targets_kam_id_1d8b43_idx',
        ),
        migrations.RenameIndex(
            model_name='targetsetting',
            new_name='kam_targets_from_da_67a2fe_idx',
            old_name='kam_targets_from_da_7d1772_idx',
        ),
        migrations.AddField(
            model_name='managertargetsetting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_targets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managertargetsetting',
            name='kam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='managertargetsetting',
            index=models.Index(fields=['kam', 'from_date', 'to_date'], name='kam_manager_kam_id_5557fa_idx'),
        ),
        migrations.AddIndex(
            model_name='managertargetsetting',
            index=models.Index(fields=['from_date', 'to_date'], name='kam_manager_from_da_574685_idx'),
        ),
        migrations.AddIndex(
            model_name='managertargetsetting',
            index=models.Index(fields=['is_fixed', 'is_locked'], name='kam_manager_is_fixe_1477cc_idx'),
        ),
    ]
