# Generated by Django 5.2.1 on 2026-02-19 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0011_managertargetsetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='kam',
            field=models.ForeignKey(blank=True, help_text='Explicit owner (KAM). Used by Plan Visit strict scoping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kam_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('SHEET', 'Sheet'), ('MANUAL', 'Manual')], db_index=True, default='SHEET', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='synced_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='visitactual',
            name='actual_datetime',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='Actual meeting/visit datetime.', null=True),
        ),
        migrations.AlterField(
            model_name='visitapprovalaudit',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DELETE', 'Delete')], max_length=16),
        ),
        migrations.AlterField(
            model_name='visitbatch',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING', 'Pending (Legacy)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING', 'Pending (Legacy)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.CreateModel(
            name='KamManagerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kam_manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kam_manager_mappings', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_kam_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kam', 'active'], name='kam_kammana_kam_id_05d670_idx'), models.Index(fields=['manager', 'active'], name='kam_kammana_manager_a550a8_idx')],
            },
        ),
    ]
