# Generated by Django 5.2.1 on 2026-02-19 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0012_customer_created_by_customer_kam_customer_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectiontxn',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectiontxn',
            name='reference_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='visitactual',
            name='meeting_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitactual',
            name='actual_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='visitbatch',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='visit_type',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('UNPLANNED', 'Unplanned')], default='PLANNED', max_length=12),
        ),
    ]
