# Generated by Django 5.2.1 on 2026-03-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0002_customer_name_unique'),
        ('kam', '0013_calllog_call_type_calllog_notes_collectionplan_notes_and_more'),
    ]

    operations = [
    ]
