# Generated by Django 5.2.1 on 2026-03-03 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0014_merge_20260303_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_period_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_exposure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='invoicefact',
            name='invoice_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoicefact',
            name='invoice_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoicefact',
            name='rate_mt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoicefact',
            name='raw_buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicefact',
            name='source_tab',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='leadfact',
            name='enquiry_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='leadfact',
            name='revenue_mt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='leadfact',
            name='source_tab',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='overduesnapshot',
            name='kam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overdue_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overduesnapshot',
            name='overdue_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='syncintent',
            name='cursor_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicefact',
            name='invoice_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoicefact',
            name='kam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicefact',
            name='qty_mt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoicefact',
            name='revenue_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoicefact',
            name='row_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leadfact',
            name='doe',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadfact',
            name='kam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadfact',
            name='qty_mt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leadfact',
            name='row_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leadfact',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='OPEN', max_length=32),
        ),
        migrations.AddIndex(
            model_name='invoicefact',
            index=models.Index(fields=['invoice_date'], name='kam_invoice_invoice_78f595_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicefact',
            index=models.Index(fields=['kam', 'invoice_date'], name='kam_invoice_kam_id_dd0b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicefact',
            index=models.Index(fields=['customer', 'invoice_date'], name='kam_invoice_custome_b1f34c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicefact',
            index=models.Index(fields=['source_tab'], name='kam_invoice_source__bfcec4_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfact',
            index=models.Index(fields=['doe'], name='kam_leadfac_doe_c45115_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfact',
            index=models.Index(fields=['kam', 'doe'], name='kam_leadfac_kam_id_8db2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfact',
            index=models.Index(fields=['source_tab'], name='kam_leadfac_source__5e1fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfact',
            index=models.Index(fields=['enquiry_no'], name='kam_leadfac_enquiry_41275d_idx'),
        ),
    ]
