# Generated by Django 5.2.1 on 2026-03-06 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0016_collectionplan_actual_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['collection_status'], name='kam_collect_collect_070fd9_idx'),
        ),
    ]
