# Generated by Django 5.2.1 on 2026-04-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0017_collectionplan_kam_collect_collect_070fd9_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitactual',
            name='confirmed_location',
        ),
    ]
