# Generated by Django 5.2.1 on 2026-04-04 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0018_remove_visitactual_confirmed_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitbatch',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitbatch',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitbatch',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitbatch',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
