# Generated by Django 5.2.1 on 2026-04-04 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0019_visitbatch_rejected_at_visitbatch_rejected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplan',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when manager rejected.', null=True),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Manager who rejected this visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by manager when rejecting. Required on rejection.', null=True),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when KAM submitted this visit to manager for approval.', null=True),
        ),
        migrations.AlterField(
            model_name='visitapprovalaudit',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DELETE', 'Delete'), ('SUBMIT', 'Submit')], max_length=16),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('PENDING', 'Pending (Legacy)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when manager approved.', null=True),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved this visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
