# Generated by Django 5.2.1 on 2026-04-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0020_visitplan_rejected_at_visitplan_rejected_by_and_more'),
        ('kam', '0021__collectionplan_null_unique_fix'),
    ]

    operations = [
    ]
