# Generated by Django 5.2.1 on 2026-04-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0022_merge_20260406_2037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontxn',
            name='row_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='Deterministic hash for idempotent sheet sync. NULL for ERP entries.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collectiontxn',
            name='source',
            field=models.CharField(choices=[('GOOGLE_SHEET', 'Google Sheet (Historical)'), ('ERP', 'ERP System Entry')], db_index=True, default='ERP', help_text='GOOGLE_SHEET = synced from sheet; ERP = entered in system', max_length=16),
        ),
        migrations.AddIndex(
            model_name='collectiontxn',
            index=models.Index(fields=['source'], name='kam_collect_source_54eba0_idx'),
        ),
        migrations.AddIndex(
            model_name='collectiontxn',
            index=models.Index(fields=['source', 'txn_datetime'], name='kam_collect_source_e1cf40_idx'),
        ),
    ]
