# Generated by Django 5.2.1 on 2026-04-09 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0023_collectiontxn_row_uuid_collectiontxn_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitplan',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee who applied this visit (universal flow). Null = old KAM-batch visit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Auto-assigned approving manager (from profile.team_leader).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
