# Generated by Django 5.2.1 on 2026-04-25 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0024_visitplan_employee_visitplan_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When overdue_amount was last synced from sheet.', null=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='overdue_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Synced from Google Sheet Overdues tab. Never manually edited.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='payment_details',
            field=models.CharField(blank=True, help_text='Mode of payment: NEFT / RTGS / Cheque / Cash / UPI etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionplan',
            name='utr_number',
            field=models.CharField(blank=True, help_text='UTR / Cheque number (optional).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount collected by KAM.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='collection_date',
            field=models.DateField(blank=True, help_text='Date actual collection was received.', null=True),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='collection_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='kam',
            field=models.ForeignKey(help_text='KAM resolved from Overdues tab column B. MANDATORY.', on_delete=django.db.models.deletion.PROTECT, related_name='collection_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] Mirrors overdue_amount for backward compat.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['customer', 'kam'], name='kam_collect_custome_3410a6_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['overdue_amount'], name='kam_collect_overdue_12c81e_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionplan',
            index=models.Index(fields=['last_synced_at'], name='kam_collect_last_sy_dc1539_idx'),
        ),
    ]
