# Generated by Django 5.2.1 on 2026-04-27 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0025_collection_plan_overdue_driven'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefact',
            name='source_status',
            field=models.CharField(blank=True, db_index=True, help_text='Raw status from source sheet, e.g. Order Converted.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='invoicefact',
            name='source_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Raw timestamp parsed from source sheet.', null=True),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='kam',
            field=models.ForeignKey(help_text='KAM resolved from Overdues tab. Required for role filtering.', on_delete=django.db.models.deletion.PROTECT, related_name='collection_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='payment_details',
            field=models.CharField(blank=True, help_text='Payment mode/details: NEFT / RTGS / Cheque / Cash / UPI etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[DEPRECATED] Mirrors overdue_amount for backward compatibility.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='collectionplan',
            name='utr_number',
            field=models.CharField(blank=True, help_text='UTR / Cheque number.', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='invoicefact',
            index=models.Index(fields=['source_tab', 'source_status'], name='kam_invoice_source__c8cc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicefact',
            index=models.Index(fields=['source_tab', 'source_status', 'invoice_date'], name='kam_invoice_source__c7613c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicefact',
            index=models.Index(fields=['kam', 'source_tab', 'source_status', 'invoice_date'], name='kam_invoice_kam_id_f7b288_idx'),
        ),
    ]
