# Generated by Django 5.2.1 on 2026-07-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0026_invoicefact_source_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KAMEmailApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_mapped_manager', models.BooleanField(default=True, help_text="Include the KAM employee's mapped reporting manager as primary recipient.")),
                ('is_active', models.BooleanField(default=True, help_text='Disable to use only the existing employee manager/CC mapping logic.')),
                ('approval_users', models.ManyToManyField(blank=True, help_text='Additional users who receive actionable KAM visit approval emails. The mapped manager is included separately when enabled.', related_name='kam_email_approval_configurations', to=settings.AUTH_USER_MODEL)),
                ('cc_users', models.ManyToManyField(blank=True, help_text='Users who receive KAM approval emails for visibility.', related_name='kam_email_cc_configurations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kam_email_approval_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KAM Approval Email Setting',
                'verbose_name_plural': 'KAM Approval Email Settings',
            },
        ),
    ]
