# Generated by Django 5.2.1 on 2025-06-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('HR', 'HR'), ('Finance', 'Finance'), ('Sales Executive', 'Sales Executive'), ('Employee', 'Employee'), ('EA', 'EA'), ('CEO', 'CEO')], max_length=50),
        ),
    ]
