# Generated by Django 5.2.1 on 2025-09-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_alter_profile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cc_override_emails',
            field=models.TextField(blank=True, default='', help_text='Admin-only: comma-separated CC emails for leave notifications.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_override_email',
            field=models.EmailField(blank=True, default='', help_text='Admin-only: override manager email for leave approvals.', max_length=254),
        ),
    ]
