# Generated by Django 5.2.1 on 2026-04-09 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reporting_officer',
            field=models.ForeignKey(blank=True, help_text="This employee's reporting manager. Auto-used in visit/leave approval.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_report_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
