# Generated by Django 5.2.1 on 2025-09-24 05:11

import apps.leave.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApproverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cc_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cc_for_approval', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approver_mapping', to=settings.AUTH_USER_MODEL)),
                ('reporting_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_for_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approver Mapping',
                'verbose_name_plural': 'Approver Mappings',
                'ordering': ['employee__id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.leave.models.leave_attachment_upload_to)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('employee_name', models.CharField(blank=True, max_length=150)),
                ('employee_email', models.EmailField(blank=True, max_length=254)),
                ('employee_designation', models.CharField(blank=True, max_length=150)),
                ('blocked_days', models.FloatField(default=0.0, help_text='How many calendar days are blocked by this leave (IST).')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('cc_person', models.ForeignKey(blank=True, help_text='HR (or other) observer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_cc', to=settings.AUTH_USER_MODEL)),
                ('cc_users', models.ManyToManyField(blank=True, help_text='Additional CC recipients selected by the employee.', related_name='leave_requests_cc_user', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('reporting_person', models.ForeignKey(blank=True, help_text='Reporting Person (manager) who must approve.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('checklist', 'Checklist'), ('delegation', 'Delegation'), ('help_ticket', 'Help Ticket')], max_length=20)),
                ('original_task_id', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('original_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='leave.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDecisionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TOKEN_OPENED', 'Token Link Opened'), ('TOKEN_APPROVE', 'Token Approve'), ('TOKEN_REJECT', 'Token Reject'), ('EMAIL_SENT', 'Email Sent'), ('HANDOVER_EMAIL_SENT', 'Handover Email Sent'), ('REMINDER_EMAIL_SENT', 'Reminder Email Sent')], max_length=25)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(blank=True, help_text='SHA256 of signed token payload.', max_length=64)),
                ('token_manager_email', models.EmailField(blank=True, max_length=254)),
                ('token_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='leave.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='DelegationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField(default=2, help_text='Send reminder every N days')),
                ('next_run_at', models.DateTimeField(help_text='Next scheduled reminder time')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to stop reminders')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='leave.leavehandover')),
            ],
            options={
                'indexes': [models.Index(fields=['next_run_at', 'is_active'], name='leave_deleg_next_ru_c7a501_idx'), models.Index(fields=['leave_handover'], name='leave_deleg_leave_h_048c62_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='leavehandover',
            index=models.Index(fields=['task_type', 'original_task_id'], name='leave_leave_task_ty_c9e373_idx'),
        ),
        migrations.AddIndex(
            model_name='leavehandover',
            index=models.Index(fields=['new_assignee'], name='leave_leave_new_ass_847a87_idx'),
        ),
        migrations.AddIndex(
            model_name='leavehandover',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='leave_leave_effecti_3d0eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='leavehandover',
            index=models.Index(fields=['is_active'], name='leave_leave_is_acti_af40dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavehandover',
            unique_together={('task_type', 'original_task_id', 'leave_request', 'new_assignee')},
        ),
        migrations.AddIndex(
            model_name='leavedecisionaudit',
            index=models.Index(fields=['leave', 'action'], name='leave_leave_leave_i_c83fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='leavedecisionaudit',
            index=models.Index(fields=['token_hash'], name='leave_leave_token_h_ccbed9_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='leave_leave_status_74e6de_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee'], name='leave_leave_employe_3c1eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['reporting_person'], name='leave_leave_reporti_1b231a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_at'], name='leave_leave_start_a_bbeff1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['end_at'], name='leave_leave_end_at_48a489_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_leave_start_d_611c6f_idx'),
        ),
    ]
