# Generated by Django 5.2.1
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approver_mapping', to=settings.AUTH_USER_MODEL)),
                ('reporting_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_for_approval', to=settings.AUTH_USER_MODEL)),
                ('cc_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_for_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approver Mapping',
                'verbose_name_plural': 'Approver Mappings',
                'ordering': ['employee__id'],
            },
        ),
    ]