# Generated by Django 5.2.1
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create ApproverMapping model
        migrations.CreateModel(
            name='ApproverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approver_mapping', to=settings.AUTH_USER_MODEL)),
                ('reporting_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_for_approval', to=settings.AUTH_USER_MODEL)),
                ('cc_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_for_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approver Mapping',
                'verbose_name_plural': 'Approver Mappings',
                'ordering': ['employee__id'],
            },
        ),
        
        # Rename existing date fields to avoid conflicts
        migrations.RenameField(
            model_name='leaverequest',
            old_name='start_date',
            new_name='old_start_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='end_date',
            new_name='old_end_date',
        ),
        
        # Add new fields to LeaveRequest
        migrations.AddField(
            model_name='leaverequest',
            name='reporting_person',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL,
                help_text='Reporting Person (manager) who must approve.'
            ),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cc_person',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='leave_requests_cc', to=settings.AUTH_USER_MODEL,
                help_text='HR (or other) observer.'
            ),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.leave.models.leave_attachment_upload_to),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_leaves', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_email',
            field=models.EmailField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='blocked_days',
            field=models.FloatField(default=0.0, help_text='How many calendar days are blocked by this leave (IST).'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        
        # Update status field choices
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(
                choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')],
                default='PENDING',
                max_length=16
            ),
        ),
        
        # Remove old fields that are replaced
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager_comment',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='hr_comment',
        ),
    ]