# Generated by Django 5.2.1 on 2025-09-24 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_fix_datetime_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leavehandover',
            index=models.Index(fields=['new_assignee', 'is_active'], name='leave_leave_new_ass_716663_idx'),
        ),
    ]
