# Generated by Django 5.2.1 on 2025-08-30 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leaverequest_options_alter_leavetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='blocked_days',
            field=models.PositiveIntegerField(default=0, help_text='How many calendar days are blocked by this leave (IST).'),
        ),
        migrations.CreateModel(
            name='LeaveDecisionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TOKEN_OPENED', 'Token Link Opened'), ('TOKEN_APPROVE', 'Token Approve'), ('TOKEN_REJECT', 'Token Reject'), ('EMAIL_SENT', 'Email Sent')], max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(blank=True, help_text='SHA256 of signed token payload.', max_length=64)),
                ('token_manager_email', models.EmailField(blank=True, max_length=254)),
                ('token_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='leave.leaverequest')),
            ],
            options={
                'indexes': [models.Index(fields=['leave', 'action'], name='leave_leave_leave_i_c83fe8_idx'), models.Index(fields=['token_hash'], name='leave_leave_token_h_ccbed9_idx')],
            },
        ),
    ]
