# Generated by Django 5.2.1 on 2025-09-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_fix_blocked_days'),
        ('leave', '0003_leaverequest_blocked_dates'),
    ]

    operations = [
    ]
