# Generated by Django 5.2.1 on 2025-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaverequest_blocked_days_leavedecisionaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='blocked_days',
            field=models.FloatField(default=0.0, help_text='How many calendar days are blocked by this leave (IST).'),
        ),
    ]
