# Generated by Django 5.2.1 on 2025-09-05 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leaverequest_blocked_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Approver Mapping',
                'verbose_name_plural': 'Approver Mappings',
                'ordering': ['employee__id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_leave_manager_0a3b5c_idx',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cc_person',
            field=models.ForeignKey(blank=True, help_text='HR (or other) observer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reporting_person',
            field=models.ForeignKey(blank=True, help_text='Reporting Person (manager) who must approve.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['reporting_person'], name='leave_leave_reporti_1b231a_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_leave_start_d_611c6f_idx'),
        ),
        migrations.AddField(
            model_name='approvermapping',
            name='cc_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_for_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvermapping',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approver_mapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvermapping',
            name='reporting_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_for_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
