# Generated by Django 5.2.1 on 2025-09-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_comprehensive_update'),
        ('leave', '0003_update_leaverequest'),
        ('leave', '0003_update_leaverequest_fields'),
        ('leave', '0006_approvermapping_and_more'),
    ]

    operations = [
    ]
