# Generated by Django 5.2.1 on 2025-09-15 09:49

import apps.leave.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_add_cc_handover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDecisionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TOKEN_OPENED', 'Token Link Opened'), ('TOKEN_APPROVE', 'Token Approve'), ('TOKEN_REJECT', 'Token Reject'), ('EMAIL_SENT', 'Email Sent')], max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(blank=True, help_text='SHA256 of signed token payload.', max_length=64)),
                ('token_manager_email', models.EmailField(blank=True, max_length=254)),
                ('token_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_leavereq_sd_ed_idx',
        ),
        migrations.RenameIndex(
            model_name='leavecc',
            new_name='leave_leave_leave_r_bdb1a2_idx',
            old_name='leave_leavecc_leave_r_f4b0e1_idx',
        ),
        migrations.RenameIndex(
            model_name='leavehandover',
            new_name='leave_leave_leave_r_04c8e7_idx',
            old_name='leave_leaveh_leave_r_a8c9f2_idx',
        ),
        migrations.RenameIndex(
            model_name='leavehandover',
            new_name='leave_leave_new_ass_716663_idx',
            old_name='leave_leaveh_new_ass_d5e1a3_idx',
        ),
        migrations.RenameIndex(
            model_name='leavehandover',
            new_name='leave_leave_origina_8c2a91_idx',
            old_name='leave_leaveh_origina_7f9b2c_idx',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='hr_comment',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager_comment',
        ),
        migrations.AlterField(
            model_name='approvermapping',
            name='cc_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cc_for_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvermapping',
            name='reporting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_for_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.leave.models.leave_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='default_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status'], name='leave_leave_status_74e6de_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee'], name='leave_leave_employe_3c1eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_at'], name='leave_leave_start_a_bbeff1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['end_at'], name='leave_leave_end_at_48a489_idx'),
        ),
        migrations.AddField(
            model_name='leavedecisionaudit',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavedecisionaudit',
            name='leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='leave.leaverequest'),
        ),
        migrations.AddIndex(
            model_name='leavedecisionaudit',
            index=models.Index(fields=['leave', 'action'], name='leave_leave_leave_i_c83fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='leavedecisionaudit',
            index=models.Index(fields=['token_hash'], name='leave_leave_token_h_ccbed9_idx'),
        ),
    ]
