# Generated by Django 5.2.1 on 2026-04-01 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_alter_leaverequest_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccconfiguration',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='interval_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='next_run_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leavedecisionaudit',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='blocked_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='cc_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='leave_requests_cc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reporting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_year_start', models.DateField(help_text='Start of leave year (always April 1, e.g. 2026-04-01)')),
                ('leave_year_end', models.DateField(help_text='End of leave year (always March 31, e.g. 2027-03-31)')),
                ('total_paid_leaves', models.PositiveIntegerField(default=24, help_text='Total paid leaves entitled per year (default 24)')),
                ('paid_leaves_taken', models.FloatField(default=0.0, help_text='Approved leave days counted as Paid (max = total_paid_leaves)')),
                ('unpaid_leaves', models.FloatField(default=0.0, help_text='Approved leave days beyond paid entitlement (Unpaid)')),
                ('remaining_paid_leaves', models.FloatField(default=24.0, help_text='Remaining paid leave days = total_paid_leaves - paid_leaves_taken')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Leave Balance',
                'verbose_name_plural': 'Employee Leave Balances',
                'ordering': ['-leave_year_start', 'employee'],
                'indexes': [models.Index(fields=['employee', 'leave_year_start'], name='leave_emplo_employe_6568b4_idx'), models.Index(fields=['leave_year_start'], name='leave_emplo_leave_y_dca1ab_idx')],
                'unique_together': {('employee', 'leave_year_start')},
            },
        ),
    ]
