# Generated by Django 5.2.1 on 2025-09-16 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_leavedecisionaudit_alter_leaverequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvermapping',
            name='cc_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_for_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvermapping',
            name='reporting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_for_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
