# Generated by Django 5.2.1 on 2026-04-01 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_add_employee_leave_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleavebalance',
            options={'ordering': ['-leave_year_start', 'employee__first_name', 'employee__last_name', 'employee__username'], 'verbose_name': 'Employee Leave Balance', 'verbose_name_plural': 'Employee Leave Balances'},
        ),
        migrations.RemoveIndex(
            model_name='employeeleavebalance',
            name='leave_emplo_leave_y_dca1ab_idx',
        ),
        migrations.AlterUniqueTogether(
            name='employeeleavebalance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='department',
            field=models.CharField(blank=True, help_text='Department or role for grouping', max_length=100),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional display name override', max_length=200),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user is available for CC selection'),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='interval_days',
            field=models.PositiveIntegerField(default=2, help_text='Send reminder every N days'),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to stop reminders'),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='next_run_at',
            field=models.DateTimeField(help_text='Next scheduled reminder time'),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='leave_year_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='leave_year_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='paid_leaves_taken',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=24, max_digits=6),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='total_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=24, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='unpaid_leaves',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='leavedecisionaudit',
            name='token_hash',
            field=models.CharField(blank=True, help_text='SHA256 of signed token payload.', max_length=64),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='blocked_days',
            field=models.FloatField(default=0.0, help_text='How many calendar days are blocked by this leave (IST).'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='cc_person',
            field=models.ForeignKey(blank=True, help_text='HR (or other) observer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text='Additional CC recipients selected by the employee from admin-configured options.', related_name='leave_requests_cc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reporting_person',
            field=models.ForeignKey(blank=True, help_text='Reporting Person (manager) who must approve.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeeleavebalance',
            index=models.Index(fields=['leave_year_start', 'leave_year_end'], name='leave_emplo_leave_y_919039_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeleavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_year_start', 'leave_year_end'), name='uniq_employee_leave_balance_year'),
        ),
    ]
