# Generated by Django 5.2.1 on 2026-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_alter_employeeleavebalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='carry_forward_adjustment',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Carry-forward penalty from previous year. Negative = excess leaves taken. e.g. -4 means this year quota = 24 - 4 = 20. Set this manually via Render shell or Django admin.', max_digits=5),
        ),
    ]
