# Generated by Django 5.2.1 on 2026-04-05 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_employeeleavebalance_carry_forward_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedecisionaudit',
            name='action',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('TOKEN_OPENED', 'Token Link Opened'), ('TOKEN_APPROVE', 'Token Approve'), ('TOKEN_REJECT', 'Token Reject'), ('EMAIL_SENT', 'Email Sent'), ('HANDOVER_EMAIL_SENT', 'Handover Email Sent'), ('REMINDER_EMAIL_SENT', 'Reminder Email Sent')], max_length=25),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reporting_person',
            field=models.ForeignKey(blank=True, help_text='Reporting Person (manager) who may approve, but approval does not control deduction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
    ]
