# Generated by Django 5.2.1 on 2026-06-04 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_alter_leavedecisionaudit_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvermapping',
            name='default_cc_users',
            field=models.ManyToManyField(blank=True, help_text='Multiple default CC recipients, admin-managed.', related_name='default_cc_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='department',
            field=models.CharField(blank=True, help_text='Department or role for grouping.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional display name override.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user is available for CC selection.'),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order. Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='ccconfiguration',
            name='user',
            field=models.ForeignKey(help_text='User who can be selected as CC recipient.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='interval_days',
            field=models.PositiveIntegerField(default=2, help_text='Send reminder every N days.'),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to stop reminders.'),
        ),
        migrations.AlterField(
            model_name='delegationreminder',
            name='next_run_at',
            field=models.DateTimeField(help_text='Next scheduled reminder time.'),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='carry_forward_adjustment',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Carry-forward adjustment from previous year or finalized master opening import. Formula used by current system: remaining = 24 + carry_forward_adjustment - deducted_leaves.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='blocked_days',
            field=models.FloatField(default=0.0, help_text='Calendar days blocked by this leave in IST. Half-day can display as 0.5.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='cc_person',
            field=models.ForeignKey(blank=True, help_text='Legacy single CC recipient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text='Additional CC recipients selected by employee.', related_name='leave_requests_cc_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reporting_person',
            field=models.ForeignKey(blank=True, help_text='Reporting Person who may approve/reject leave.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
    ]
