# Generated by Django 5.2.1 on 2026-07-23 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_alter_approvermapping_default_cc_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Apply this global Leave email recipient configuration.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cc_users', models.ManyToManyField(blank=True, help_text='Active users copied on every Leave notification email.', related_name='global_leave_email_cc_settings', to=settings.AUTH_USER_MODEL)),
                ('excluded_users', models.ManyToManyField(blank=True, help_text='Users whose email addresses must be removed from Leave notification CC lists, including legacy and employee-specific mappings.', related_name='excluded_from_leave_email_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Email Settings',
                'verbose_name_plural': 'Leave Email Settings',
            },
        ),
    ]
