# Generated by Django 5.2.1 on 2026-07-23 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_leaveemailsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveemailsettings',
            name='excluded_users',
        ),
        migrations.AddField(
            model_name='leaveemailsettings',
            name='to_users',
            field=models.ManyToManyField(blank=True, help_text='Active users added to TO on every Leave notification email.', related_name='global_leave_email_to_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveemailsettings',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text='Active users added to CC on every Leave notification email.', related_name='global_leave_email_cc_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
