# Generated by Django 5.2.1 on 2026-07-29 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0021_remove_leaveemailsettings_excluded_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='opening_adjustment',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Manual opening adjustment, kept separate from carry forward.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='cc_users',
            field=models.ManyToManyField(blank=True, help_text='Legacy field. Employee-selected CC is ignored for leave email routing.', related_name='leave_requests_cc_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
