# Auto-generated by setup
param()
$PROJECT_DIR = "E:\CLIENT PROJECT\employee management system bos\employee_management_system"
$VENV_PY    = "$PROJECT_DIR\.venv\Scripts\python.exe"

Set-Location $PROJECT_DIR
& $VENV_PY ".\manage.py" send_weekly_congrats
