# Generated by Django 5.2.1 on 2025-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycommitment',
            name='audit_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weeklycommitment',
            name='checklist_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weeklycommitment',
            name='delegation_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weeklycommitment',
            name='fms_desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
