# Generated by Django 5.2.1 on 2025-07-15 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_weeklycommitment_audit_desc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklycommitment',
            options={},
        ),
        migrations.AddField(
            model_name='weeklycommitment',
            name='checklist_ontime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklycommitment',
            name='checklist_ontime_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklycommitment',
            name='delegation_ontime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklycommitment',
            name='delegation_ontime_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='audit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='audit_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='checklist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='checklist_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='delegation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='delegation_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='fms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='fms_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklycommitment',
            name='week_start',
            field=models.DateField(),
        ),
    ]
