# Generated by Django 5.2.1 on 2025-07-15 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_weeklycommitment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(default='Daily', max_length=20)),
                ('actual_duration_minutes', models.IntegerField(default=0)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(default=0)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
