# Generated by Django 5.2.1 on 2025-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_checklist_delegation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklycommitment',
            options={'verbose_name': 'Weekly Commitment', 'verbose_name_plural': 'Weekly Commitments'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='planned_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
