# Generated by Django 5.2.1 on 2025-08-10 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_weeklycommitment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='assign_to',
        ),
        migrations.AlterUniqueTogether(
            name='weeklycommitment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='weeklycommitment',
            index=models.Index(fields=['user', 'week_start'], name='idx_wc_user_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklycommitment',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_weekly_commitment_user_week'),
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='Delegation',
        ),
    ]
