# Generated by Django 5.2.1 on 2025-10-07 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_checklist_assign_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mailed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Score',
                'verbose_name_plural': 'Weekly Scores',
                'indexes': [models.Index(fields=['user', 'week_start'], name='idx_ws_user_week'), models.Index(fields=['week_start'], name='idx_ws_week')],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_weekly_score_user_week')],
            },
        ),
    ]
